FROM python:3.10-slim

ENV PYTHONUNBUFFERED=1
WORKDIR /app

# Instala SOLO las dependencias de runtime
COPY requirements_api.txt .
RUN pip install --upgrade pip \
 && pip install --no-cache-dir -r requirements_api.txt

# Copia el código y arranca FastAPI
COPY . .
EXPOSE 8080
CMD ["uvicorn", "api.api:app", "--host", "0.0.0.0", "--port", "8080"]
